### ISSUE TITLE
Add engine support for node 6.x LTS

### ISSUE THREAD

**Issue by daprahamian** [factset/labeledpipe#7]
Since Node 6 is now LTS, it would be cool if we could update the engine field to allow Node 6.

**Comment by destroyerofbuilds** [comment]
We will want to also add Node version 6 to the `.travis.yml` file before this change, or as part of this change.

**Comment by destroyerofbuilds** [comment]
Version [2.0.0](https://github.com/factset/labeledpipe/releases/tag/2.0.0) has been released.
